AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 10
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Page Speed function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pagespeed/
  HelloWorldFunction:
    Description: Page Speed Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PageSpeedFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Page Speed function
    Value:
      Fn::GetAtt:
      - PageSpeedFunctionRole
      - Arn
Resources:
  PageSpeedFunction:
    Properties:
      CodeUri: s3://td-sam-hello-world/57189f3882fe263e99e6d4dc9dcd2b0a
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        PageSpeed:
          Properties:
            Method: post
            Path: /pagespeed
          Type: Api
      Handler: HelloWorld::HelloWorld.PageSpeed::PageSpeedHandler
      Runtime: dotnetcore2.0
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
